# Generated by Django 5.2.4 on 2025-08-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_researchgroupcomponent_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchgroupcomponent',
            old_name='username',
            new_name='user',
        ),
    ]
